### ISSUE TITLE
bug: cannot select APK from storage on <A11 devices.

### ISSUE THREAD

**Issue by Canny1913** [revanced/revanced-manager-compose#16]
### Type

Error at runtime

### Bug description

Manager crashes on devices using <A11 when users try to patch an APK that was selected from device storage.
This seems to be caused by PackageParser returning null when manager attempts to parse the selected APK.

### Steps to reproduce

1)Select an APK from storage
2)Attempt to go to patches selection screen.

### Android version

Below 11 (API level 31).

### Manager version

N/A

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
11-12 19:48:56.481  4059  4059 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.compose/cache/1274 Binary XML file line #41
11-12 19:48:56.804  1707  1707 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3220
11-12 19:48:56.805  1707  1707 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2085 repeatCheckTimes = 0, unlocked = true
11-12 19:48:56.806  1707  1707 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1876 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=app.revanced.manager.compose fieldId=-1 fieldName=null extras=null}, false)
11-12 19:48:56.808  1707  1707 I GoogleInputMethodService: GoogleInputMethodService.shouldHideHeaderOnInitialState():3985 ShouldHideHeaderOnInitialState = false
11-12 19:48:56.809  1707  1707 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2085 repeatCheckTimes = 2, unlocked = true
11-12 19:48:57.228 25510 25510 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.feedback.internal.IFeedbackService dat=chimera-action: cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
11-12 19:48:57.266   527   591 E SurfaceFlinger: Failed to remove layer from mapping - could not find matching layer
--------- beginning of crash
11-12 19:48:57.714  4059  4059 E AndroidRuntime: FATAL EXCEPTION: main
11-12 19:48:57.714  4059  4059 E AndroidRuntime: Process: app.revanced.manager.compose, PID: 4059
11-12 19:48:57.714  4059  4059 E AndroidRuntime: java.lang.NullPointerException
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at java.io.File.<init>(File.java:283)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:4800)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at app.revanced.manager.patcher.PatcherUtils.getSelectedPackageInfo(PatcherUtils.kt:39)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at app.revanced.manager.ui.screen.subscreens.PatchesSelectorSubscreenKt.PatchesSelectorSubscreen(PatchesSelectorSubscreen.kt:294)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at app.revanced.manager.MainActivity$onCreate$2$1$3.invoke(MainActivity.kt:110)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at com.xinto.taxi.TaxiKt$Taxi$1$1.invoke(Taxi.kt:48)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:32)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:125)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at com.xinto.taxi.TaxiKt$Taxi$1.invoke(Taxi.kt:49)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:46)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:92)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:10)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:1871)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:29)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:224)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:150)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:7)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at com.xinto.taxi.TaxiKt.Taxi(Taxi.kt:195)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at com.xinto.taxi.TaxiKt$Taxi$2.invoke(Taxi.kt:23)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:299)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:116)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:49)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:127)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:36)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:18)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:75)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:351)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:11)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1002)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:816)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:748)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6692)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-12 19:48:57.714  4059  4059 E AndroidRuntime:        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@81b48e2, androidx.compose.ui.platform.MotionDurationScaleImpl@49f1473, StandaloneCoroutine{Cancelling}@3e8ef30, AndroidUiDispatcher@22ea7a9]
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
N/A
```

### Screenshots or videos

N/A

### Solution

Figure out why PackageParser returns null then fix it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
Fixed with 1f76704f950b58c3fa49ab7a96f21e3a88562307
